# Expression generated by update.sh; do not edit it by hand!
# Brave Origin publishes prerelease assets per platform, so update.sh rewrites
# this whole matrix only after the expected release asset exists.
# Source: modules/_pkgs/brave-origin/update.sh and https://versions.brave.com/
{ callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.92.20";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_amd64.deb";
      hash = "sha256-jx8NxhiZP+kqdl0SZXj41GFaKaTHHG9f2v2p/4SUSD4=";
    };
    aarch64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-v${version}-darwin-arm64.zip";
      hash = "sha256-NXXgjXeFKiZAJqxynmNNFg/UAmf9uClb9nN5t1pXc0U=";
    };
    x86_64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-v${version}-darwin-x64.zip";
      hash = "sha256-1+spOMMVXrSHTZqWzHSXB8cEukZdhj2+RtDgEp4r+KQ=";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
