# Expression generated by update.sh; do not edit it by hand!
# Brave Origin publishes prerelease assets per platform, so update.sh rewrites
# this whole matrix only after the expected release asset exists.
# Source: modules/_pkgs/brave-origin/update.sh and https://versions.brave.com/
{ callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.92.91";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_amd64.deb";
      hash = "sha256-Z8Ot/srJ2RfeAFOmqcRZHD6cceKpMFIs+g64N175NVE=";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
