{
  inputs,
  self,
  pkgs,
  ...
}:
{
  # MCP server configuration shared between configs and project templates.
  gh_grep = {
    # Fast AST-based regex search over public GitHub repositories.
    type = "remote";
    url = "https://mcp.grep.app/";
    enabled = true;
    timeout = 20000;
  };

  context7 = {
    # Advanced documentation index for up-to-date API lookups.
    type = "remote";
    url = "https://mcp.context7.com/mcp";
    enabled = true;
    timeout = 20000;
  };

  daisyui = {
    # Manage UI components using DaisyUI schemas.
    type = "local";
    command = [ "${self.packages.${pkgs.stdenv.hostPlatform.system}.daisyui-mcp}/bin/daisyui-mcp" ];
    enabled = false;
    timeout = 20000;
  };

  markdown_lint = {
    # Lint Markdown files to keep generated docs compatible with repo rules.
    type = "local";
    command = [
      "${inputs.self.packages.${pkgs.stdenv.hostPlatform.system}.markdown-lint-mcp}/bin/markdown-lint-mcp"
    ];
    enabled = true;
    timeout = 10000;
  };

  qmllint = {
    # Validate Qt/QML syntax for widget configuration work.
    type = "local";
    command = [
      "${inputs.self.packages.${pkgs.stdenv.hostPlatform.system}.qmllint-mcp}/bin/qmllint-mcp"
    ];
    enabled = false;
    timeout = 20000;
  };

  quickshell = {
    # Read documentation for the custom Quickshell compositor stack.
    type = "local";
    command = [
      "${
        inputs.self.packages.${pkgs.stdenv.hostPlatform.system}.quickshell-docs-mcp
      }/bin/quickshell-docs-mcp"
    ];
    enabled = false;
    timeout = 20000;
  };

  # Remote tool: High-quality parallel web search with deep research capabilities.
  # Already declared by Oh-My-OpenAgent.
  # websearch = {
  #   type = "remote";
  #   url = "https://mcp.exa.ai/mcp?exaApiKey=${self.secrets.EXA_API_KEY}&tools=web_search_exa,deep_search_exa,get_code_context_exa,crawling_exa,deep_researcher_start,deep_researcher_check";
  #   enabled = true;
  #   timeout = 30000;
  # };

  image_gen = {
    # Generate images with the first configured model that exposes image output.
    type = "local";
    command = [
      (pkgs.writeShellScript "image-gen-mcp-wrapper" ''
        export CLIPROXYAPI_KEY="${self.secrets.CLIPROXYAPI_KEY}"

        # Prefer the first model in models.json that advertises image output.
        # Source for model capabilities: modules/nixos/terminal/opencode/models.json
        # (generated by sync_models() from CliProxyApi supportedOutputModalities).
        IMAGE_MODEL="$(${pkgs.jq}/bin/jq -r '
          first(
            .providers
            | to_entries[]
            | .key as $provider
            | .value.models
            | to_entries[]
            | select(((.value.modalities.output // []) | index("image")) != null)
            | "\($provider)/\(.key)"
          ) // empty
        ' ${./models.json})"

        exec ${pkgs.bun}/bin/bun ${../../../nixos/scripts/bunjs/mcp/image-gen.ts}
      '')
    ];
    enabled = true;
    timeout = 60000;
  };
}
